// This file was generated by lib-showcase-engine on Fri Oct 09 2020
// You can extend it if you want, but leave the defaults to be required from the engine config

module.exports = {
  ...require('./node_modules/@meliuz-training/lib-showcase-engine/tools/engine_cli/etc/metro.config')
};
